<div class="content-wrapper" style="min-height: 900px;">
	<!-- Content Header (Page header) -->
	<section class="content-header">
	  <h1>
		Add Page
		<small>form to enter Sales Details</small>
	  </h1>
	  <ol class="breadcrumb">
		<li><a href="/Index"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Add Page</li>
	  </ol>
	</section>
	
	<!-- Main content -->
	<section class="content">
		<div class="row">
			<div class="col-md-1"></div>
			<div class="col-md-10">
				<div class="box">
					<div class="box-header">
					  <h3 class="box-title">Add Sales Form </h3>
					</div><!-- /.box-header -->
					<div class="box-body">
						<form role="form" method="POST" action="/Index/add">
						  <div class="form-group">
							<label for="mgr_id"><span class="validationNeed">*</span>Id :</label>
							<input type="number" class="form-control" id="mgr_id" name="mgr_id" required >
						  </div>
						  <div class="form-group">
							<label for="mgr_name"><span class="validationNeed">*</span>Name :</label>
							<input type="text" class="form-control" id="mgr_name" name="mgr_name" required>
						  </div>
						  <div class="form-group">
							<label for="mgr_sales"><span class="validationNeed">*</span>Sales ( % ) :</label>
							<input type="number" maxlength="2" class="form-control" id="mgr_sales" name="mgr_sales" required>
						  </div>
						  <div class="form-group">
							<label for="mgr_zip"><span class="validationNeed">*</span>Zipcode :</label>
							<input type="number" maxlength="6"  class="form-control" id="mgr_zip" name="mgr_zip" required>
						  </div>
						  <button type="submit" class="btn btn-default">Add</button>
						</form>
					 
					</div><!-- /.box-body -->
					
				  </div>
			</div>
			<div class="col-md-1"></div>
		</div>
	</section>
</div>
		