<div class="content-wrapper deleteWrapper">
	<!-- Content Header (Page header) -->
	<section class="content-header">
	  <h1>
		Delete Page
	  </h1>
	  <ol class="breadcrumb">
		<li><a href="/Index"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Delete Page</li>
	  </ol>
	</section>
	
	<!-- Main content -->
	<section class="content">
		<div class="row">
			<div class="col-md-1"></div>
			<div class="col-md-10">
				<div class="box">
					<div class="box-header">
					  <h3 class="box-title">Record Deleted Successfully </h3>
					</div><!-- /.box-header -->
					<div class="box-body">
						<a href="/Index">Click here to see the List of Sales....</a>					 
					</div><!-- /.box-body -->
					
				  </div>
			</div>
			<div class="col-md-1"></div>
		</div>
	</section>
</div>
		