<div class="content-wrapper" style="min-height: 900px;">
	<!-- Content Header (Page header) -->
	<section class="content-header">
	  <h1>
		Edit Page
		<small>form to enter Sales Details</small>
	  </h1>
	  <ol class="breadcrumb">
		<li><a href="/Index"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">Edit Page</li>
	  </ol>
	</section>
	<?php
		$mgr_sales =Zend_Registry::get('mgr_sales');
		$request = new Zend_Controller_Request_Http();
		$ref = $request->getParam('ref');
	?>
	<!-- Main content -->
	<section class="content">
		<div class="row">
			<div class="col-md-1"></div>
			<div class="col-md-10">
				<div class="box">
					<div class="box-header">
					  <h3 class="box-title">Edit Sales Form </h3>
					</div><!-- /.box-header -->
					<div class="box-body">
						<form role="form" method="POST" action="/Index/edit?ref=<?php echo $ref;?>">
						  <div class="form-group">
							<label for="mgr_id">Id :</label>
							<input type="number" class="form-control" id="mgr_id" name="mgr_id" value="<?php echo $mgr_sales[$ref]['mgr_id'];?>" readonly >
						  </div>
						  <div class="form-group">
							<label for="mgr_name"><span class="validationNeed">*</span>Name :</label>
							<input type="text" class="form-control" id="mgr_name" name="mgr_name" value="<?php echo $mgr_sales[$ref]['mgr_name'];?>" required>
						  </div>
						  <div class="form-group">
							<label for="mgr_sales"><span class="validationNeed">*</span>Sales ( % ) :</label>
							<input type="number" max="2" min="2" class="form-control" id="mgr_sales" name="mgr_sales" value="<?php echo $mgr_sales[$ref]['mgr_sales'];?>" required>
						  </div>
						  <div class="form-group">
							<label for="mgr_zip"><span class="validationNeed">*</span>Zipcode :</label>
							<input type="number" max="6" min="6" class="form-control" id="mgr_zip"  name="mgr_zip" value="<?php echo $mgr_sales[$ref]['mgr_zip'];?>" required >
						  </div>
						  <button type="submit" class="btn btn-default">Update</button>
						</form>
					 
					</div><!-- /.box-body -->
					
				  </div>
			</div>
			<div class="col-md-1"></div>
		</div>
	</section>
</div>