<div class="content-wrapper" >
	<!-- Content Header (Page header) -->
	<section class="content-header">
	  <h1>
		List Page		
	  </h1>
	  <div class="actionHolder"><a href="Index/add">add</a></div>
	  <ol class="breadcrumb">
		<li><a href="/Index"><i class="fa fa-dashboard"></i> Home</a></li>
		<li class="active">List Page</li>
	  </ol>
	</section>
	<!-- Main content -->
	<section class="content">
		<div class="row">
			<div class="col-md-1"></div>
			<div class="col-md-10">
				<div class="box">
					<div class="box-header">
					  <h3 class="box-title">Current Month Sales</h3>
					</div><!-- /.box-header -->
					<div class="box-body">
					  <table id="tblSalesInfo" class="table table-bordered">
						<thead>
							<tr>
							  <th style="width: 10px">Id</th>
							  <th>Manager Name</th>
							  <th class="text-center">Sales %</th>
							  <th style="width: 40px">Zipcode</th>
							  <th style="width: 40px">Details</th>
							  <th style="width: 40px">Edit</th>
							  <?php if(count($this->mgr_sales) > 1 ){?>
							  <th style="width: 40px">Delete</th>
							  <?php }?>
							</tr>
						</thead>
						<tbody>
						<?php 
						foreach ($this->mgr_sales as  $key=>$value){
						?>
						<tr>
						  <td><?php echo $value['mgr_id'];?></td>
						  <td><?php echo $value['mgr_name'];?></td>
						  <td class="text-center">
							<?php echo $value['mgr_sales'];?>
						  </td>
						  <td><?php echo $value['mgr_zip'];?></td>
						  <td style="width: 40px; text-align:center;"><a href="/Index/view/ref/<?php echo $key;?>"><i class="fa fa-list"></i></td>
						  <td style="width: 40px; text-align:center;"><a href="/Index/edit/ref/<?php echo $key;?>"><i class="fa fa-edit"></i></td>
						  <?php if(count($this->mgr_sales) > 1 ){?>
						  <td style="width: 40px; text-align:center;" ><a onClick="javascript:return confirm('Are you sure?');" href="/Index/delete/ref/<?php echo $key;?>"><i class="fa fa-trash"></i></a></td>
						  <?php } ?>
						</tr>
						<?php
						}
						?>								
					  </tbody></table>
					</div><!-- /.box-body -->
					
				  </div>
			</div>
			<div class="col-md-1"></div>
		</div>
	</section>
</div>

<script>
$(function(){
	$('#tblSalesInfo').DataTable();
});
$(document).ready(function(){
   // $('#tblSalesInfo').DataTable();
});
</script>
		
		
		