<form name='frmLogin' method='post' action='index'>
<div class="login-page"> 
	<div class="login-box">
		<div class="login-logo">
			<b>Test</b>App
		</div><!-- /.login-logo -->
		
		<div class="login-box-body">
			<p class="login-box-msg">Sign in to start your session</p>
			  <div class="form-group has-feedback">
				<input name="txtUsername" type="text" class="form-control" placeholder="User Name"/>
				<span class="glyphicon glyphicon-envelope form-control-feedback"></span>
			  </div>
			  <div class="form-group has-feedback">
				<input name="txtPassword" type="password" class="form-control" placeholder="Password"/>
				<span class="glyphicon glyphicon-lock form-control-feedback"></span>
			  </div>
			  <div class="row">
				<div class="col-xs-4 pull-right">
				  <button id="btnSignIn" type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
				</div><!-- /.col -->
			  </div>
			 
			<br />
		</div><!-- /.login-box-body -->
	</div><!-- /.login-box -->
</div>
</form>