<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Salesman Info</title>
  <?php 
	$this->headLink()->appendStylesheet(MEDIA_PATH.'css/bootstrap.css'); 
	$this->headLink()->appendStylesheet(MEDIA_PATH.'css/font-awesome.min.css');
	$this->headLink()->appendStylesheet(MEDIA_PATH.'css/testapp.css');
	$this->headLink()->appendStylesheet(MEDIA_PATH.'css/jquery.dataTables.min.css');
	
	// rendering the links from the layout:
	echo $this->headLink();
  ?>

  <?php 
	$this->headScript()->appendFile(MEDIA_PATH."js/jQuery-2.1.3.min.js");
	$this->headScript()->appendFile(MEDIA_PATH."js/bootstrap.min.js");
	$this->headScript()->appendFile(MEDIA_PATH."js/jquery.dataTables.min.js");
	
	// rendering the script from the layout:
	echo $this->headScript();
  ?>
  
  <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
  
</head>
<body>
<div class="layout-top-nav">
	<div class="wrapper">	
		<?php if(strtolower($_SERVER['REQUEST_URI']) != '/login') {?>
			<header class="main-header">               
				<nav class="navbar navbar-static-top">
				  <div class="container-fluid">
					  <div class="navbar-header">
						<a href="/Index" class="navbar-brand"><b>Salesman </b>Info</a>
						<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
						  <i class="fa fa-bars"></i>
						</button>
					  </div>

					  <div class="collapse navbar-collapse" id="navbar-collapse">            
						<ul class="nav navbar-nav navbar-right">
						  <li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">Hello Administrator! <span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
							  <li><a href="/logout">Logout</a></li>
							</ul>
						  </li>
						</ul>
					  </div><!-- /.navbar-collapse -->
				  </div><!-- /.container-fluid -->
				</nav>
			</header>		
		<?php }?>
		
		<?php echo $this->layout()->content ?>
		
		<?php if(strtolower($_SERVER['REQUEST_URI']) != '/login') {?>
			<footer class="main-footer">	
				<div class="pull-right hidden-xs">
				  <b>Salesman </b>Info
				</div>
				<strong>Powered by Advanced JSCOE.</strong> All rights reserved.
			</footer>	
		<?php }?>
	</div><!-- /.wrapper -->
</div>
</body>
</html>