<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>TestApp</title>
  <?php echo $this->headLink()->appendStylesheet('css/bootstrap.css') ?>
  <?php echo $this->headLink()->appendStylesheet('css/font-awesome.min.css') ?>
  <?php echo $this->headLink()->appendStylesheet('css/testapp.css') ?>
  
  
  <?php echo $this->headScript()->prependFile( "js/jQuery-2.1.3.min.js", $type = 'text/javascript' ) ?>
  <?php echo $this->headScript()->prependFile( "js/bootstrap.min.js", $type = 'text/javascript' ) ?>
  
</head>
<body>
 
<?php echo $this->layout()->content ?>

</body>
</html>